import { writeFile } from 'node:fs/promises'

const FINRA_URL = 'https://www.finra.org/rules-guidance/key-topics/margin-accounts/margin-statistics'
const FRED = {
  highYieldOas: 'https://fred.stlouisfed.org/graph/fredgraph.csv?id=BAMLH0A0HYM2',
  fedAssets: 'https://fred.stlouisfed.org/graph/fredgraph.csv?id=WALCL',
}

function parseNumber(value) {
  return Number(value.replaceAll(',', '').trim())
}

function toIsoMonth(value) {
  const [month, year] = value.split('-')
  const months = { Jan: '01', Feb: '02', Mar: '03', Apr: '04', May: '05', Jun: '06', Jul: '07', Aug: '08', Sep: '09', Oct: '10', Nov: '11', Dec: '12' }
  return `20${year}-${months[month]}`
}

function csvPoints(text) {
  const points = text.trim().split(/\r?\n/).slice(1).flatMap((row) => {
    const [asOf, raw] = row.split(',')
    if (!asOf || !raw || raw === '.') return []
    const value = Number(raw)
    return Number.isFinite(value) ? [{ asOf, value }] : []
  })
  if (!points.length) throw new Error('No numeric FRED observations found')
  return points
}

function percentileAtOrBelow(values, value) {
  if (!values.length) throw new Error('Cannot calculate a percentile without observations')
  return (values.filter((candidate) => candidate <= value).length / values.length) * 100
}

function latestWithHistoricalPercentile(text, label) {
  const points = csvPoints(text)
  const latest = points.at(-1)
  if (!latest) throw new Error(`${label} did not include a latest observation`)
  const lookbackPoints = points.slice(-2_520)
  return {
    ...latest,
    statistics: {
      observations: lookbackPoints.length,
      historicalPercentile: percentileAtOrBelow(lookbackPoints.map((point) => point.value), latest.value),
    },
  }
}

const [finraResponse, oasResponse, assetsResponse] = await Promise.all([
  fetch(FINRA_URL),
  fetch(FRED.highYieldOas),
  fetch(FRED.fedAssets),
])

if (!finraResponse.ok || !oasResponse.ok || !assetsResponse.ok) {
  throw new Error(`Source request failed: FINRA ${finraResponse.status}, OAS ${oasResponse.status}, assets ${assetsResponse.status}`)
}

const [finraPage, oasCsv, assetsCsv] = await Promise.all([
  finraResponse.text(),
  oasResponse.text(),
  assetsResponse.text(),
])

const finraRows = [...finraPage.matchAll(/<tr><td>([A-Z][a-z]{2}-\d{2})<\/td><td>([\d,]+)<\/td><td>([\d,]+)<\/td><td>([\d,]+)<\/td><\/tr>/g)].map((match) => ({
  asOf: toIsoMonth(match[1]),
  debitMillions: parseNumber(match[2]),
  freeCashMillions: parseNumber(match[3]),
  freeMarginMillions: parseNumber(match[4]),
}))
if (finraRows.length < 2) throw new Error('Unable to parse the FINRA margin statistics table')

const latestFinra = finraRows[0]
const oas = latestWithHistoricalPercentile(oasCsv, 'High-yield OAS')
const assets = latestWithHistoricalPercentile(assetsCsv, 'Federal Reserve assets')
const output = `// Generated by scripts/refresh-us-data.mjs. Do not edit by hand.\nexport const latestUS = ${JSON.stringify({
  refreshedAt: new Date().toISOString().slice(0, 10),
  finra: {
    ...latestFinra,
    history: finraRows.slice().reverse(),
  },
  fred: {
    highYieldOas: oas,
    fedAssets: { asOf: assets.asOf, millions: assets.value, statistics: assets.statistics },
  },
}, null, 2)} as const\n`

await writeFile(new URL('../src/generated/latestUs.ts', import.meta.url), output)
