"""Build the current JPX aggregate from the official daily XLS file.

This script is intentionally kept outside the browser bundle. It only accepts the
official JPX host and writes a small generated TypeScript snapshot for the build.
"""

from hashlib import sha256
import json
from pathlib import Path
import re
from urllib.parse import urljoin
from urllib.request import urlopen

import xlrd

INDEX_URL = "https://www.jpx.co.jp/english/markets/statistics-equities/margin/index.html"
ROOT_URL = "https://www.jpx.co.jp"


def get_bytes(url: str) -> bytes:
    with urlopen(url, timeout=30) as response:
        return response.read()


def numeric(value):
    return isinstance(value, (int, float)) and not isinstance(value, bool)


index = get_bytes(INDEX_URL).decode("utf-8")
match = re.search(r'href="([^"]*mtdailyk\d{8,14}\.xls)"', index)
if not match:
    raise RuntimeError("Unable to locate the current JPX margin XLS file")

source_url = urljoin(ROOT_URL, match.group(1))
source_bytes = get_bytes(source_url)
workbook = xlrd.open_workbook(file_contents=source_bytes)
sheet = workbook.sheet_by_index(0)
as_of = ""
for cell in sheet.row_values(1):
    if isinstance(cell, str) and "as of" in cell:
        date_match = re.search(r"(\d{4})/(\d{1,2})/(\d{1,2})", cell)
        if date_match:
            as_of = "-".join(part.zfill(2) if i else part for i, part in enumerate(date_match.groups()))
        break

sales = 0
purchases = 0
issues = 0
for row_index in range(7, sheet.nrows):
    row = sheet.row_values(row_index)
    if len(row) <= 11 or not numeric(row[8]) or not numeric(row[11]):
        continue
    sales += int(row[8])
    purchases += int(row[11])
    issues += 1

if not as_of or not issues or not sales:
    raise RuntimeError("JPX file did not contain a usable aggregate")

snapshot = {
    "refreshedAt": as_of,
    "asOf": as_of,
    "sourceUrl": source_url,
    "sourceHash": f"sha256:{sha256(source_bytes).hexdigest()}",
    "issues": issues,
    "outstandingSales": sales,
    "outstandingPurchases": purchases,
}
repo = Path(__file__).resolve().parents[1]
archive_relative_path = Path("data") / "raw" / "jp" / f"{as_of}-{sha256(source_bytes).hexdigest()[:12]}.xls"
archive = repo / archive_relative_path
archive.parent.mkdir(parents=True, exist_ok=True)
if not archive.exists():
    archive.write_bytes(source_bytes)

snapshot["archiveRelativePath"] = archive_relative_path.as_posix()
snapshot["archiveUrl"] = f"https://raw.githubusercontent.com/x-tong/leverage-liquidity-radar/main/{archive_relative_path.as_posix()}"
target = repo / "src" / "generated" / "latestJp.ts"
target.write_text("// Generated by scripts/refresh-japan-data.py. Do not edit by hand.\nexport const latestJP = " + json.dumps(snapshot, ensure_ascii=False, indent=2) + " as const\n", encoding="utf-8")
