import { writeFile } from 'node:fs/promises'

const FINRA_URL = 'https://www.finra.org/rules-guidance/key-topics/margin-accounts/margin-statistics'
const FRED = {
  highYieldOas: 'https://fred.stlouisfed.org/graph/fredgraph.csv?id=BAMLH0A0HYM2',
  fedAssets: 'https://fred.stlouisfed.org/graph/fredgraph.csv?id=WALCL',
}

function parseNumber(value) {
  return Number(value.replaceAll(',', '').trim())
}

function toIsoMonth(value) {
  const [month, year] = value.split('-')
  const months = { Jan: '01', Feb: '02', Mar: '03', Apr: '04', May: '05', Jun: '06', Jul: '07', Aug: '08', Sep: '09', Oct: '10', Nov: '11', Dec: '12' }
  return `20${year}-${months[month]}`
}

function latestCsvPoint(text) {
  const rows = text.trim().split(/\r?\n/).slice(1)
  for (let index = rows.length - 1; index >= 0; index -= 1) {
    const [date, raw] = rows[index].split(',')
    if (raw && raw !== '.') return { asOf: date, value: Number(raw) }
  }
  throw new Error('No numeric FRED observation found')
}

const [finraResponse, oasResponse, assetsResponse] = await Promise.all([
  fetch(FINRA_URL),
  fetch(FRED.highYieldOas),
  fetch(FRED.fedAssets),
])

if (!finraResponse.ok || !oasResponse.ok || !assetsResponse.ok) {
  throw new Error(`Source request failed: FINRA ${finraResponse.status}, OAS ${oasResponse.status}, assets ${assetsResponse.status}`)
}

const [finraPage, oasCsv, assetsCsv] = await Promise.all([
  finraResponse.text(),
  oasResponse.text(),
  assetsResponse.text(),
])

const finraRows = [...finraPage.matchAll(/<tr><td>([A-Z][a-z]{2}-\d{2})<\/td><td>([\d,]+)<\/td><td>([\d,]+)<\/td><td>([\d,]+)<\/td><\/tr>/g)].map((match) => ({
  asOf: toIsoMonth(match[1]),
  debitMillions: parseNumber(match[2]),
  freeCashMillions: parseNumber(match[3]),
  freeMarginMillions: parseNumber(match[4]),
}))
if (finraRows.length < 2) throw new Error('Unable to parse the FINRA margin statistics table')

const latestFinra = finraRows[0]
const oas = latestCsvPoint(oasCsv)
const assets = latestCsvPoint(assetsCsv)
const output = `// Generated by scripts/refresh-us-data.mjs. Do not edit by hand.\nexport const latestUS = ${JSON.stringify({
  refreshedAt: new Date().toISOString().slice(0, 10),
  finra: {
    ...latestFinra,
    history: finraRows.slice().reverse(),
  },
  fred: {
    highYieldOas: oas,
    fedAssets: { asOf: assets.asOf, millions: assets.value },
  },
}, null, 2)} as const\n`

await writeFile(new URL('../src/generated/latestUs.ts', import.meta.url), output)
